# Generated by Django 4.2.26 on 2025-11-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_timeslot_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='chosen_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='chosen_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
