# Generated by Django 4.2.26 on 2025-11-25 17:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_meeting_chosen_end_meeting_chosen_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='invite_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
